# Generated by Django 4.2.4 on 2023-08-12 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('nick_name', models.CharField(default='익명', max_length=10, verbose_name='닉네임')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11, verbose_name='휴대폰 번호')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='이메일 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_social', models.BooleanField(default=False, verbose_name='소셜로그인 유저')),
                ('social_id', models.CharField(default='', max_length=20, verbose_name='소셜로그인 ID')),
                ('progress', models.IntegerField(choices=[(0, 'Bookmark'), (1, 'Signup'), (2, 'Login'), (3, 'Community'), (4, 'Write'), (5, 'Communicate'), (6, 'Mypage')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
