# Generated by Django 4.2.3 on 2023-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=10, null=True, verbose_name='nick_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='phone_number'),
        ),
    ]
