# Generated by Django 4.2.3 on 2023-08-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_reseted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
