# Generated by Django 4.2.3 on 2023-08-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name_user_nick_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='own_name',
        ),
    ]
