# Generated by Django 4.2.3 on 2023-08-06 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 6, 14, 14, 50, 394856, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
