# Generated by Django 4.2.3 on 2023-08-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='익명', max_length=10, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_name',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='회원 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='휴대폰 번호'),
        ),
    ]
