# Generated by Django 4.2.3 on 2023-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(default='', max_length=20, verbose_name='소셜로그인 ID'),
        ),
    ]
