# Generated by Django 4.2.3 on 2023-08-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningProgress',
        ),
    ]
